### ISSUE TITLE
covrpage installation

### ISSUE THREAD

**Issue by maelle** [metrumresearchgroup/covrpage#53]
:wave: any idea why I get https://travis-ci.org/maelle/trying.lockedata.starters/builds/480813189#L2111 ?

It's supposed to get installed before getting used cf https://github.com/maelle/trying.lockedata.starters/blob/master/tic.R

**Comment by yonicd** [comment]
what version of remotes are you using?

```r
remotes::install
Error: 'install' is not an exported object from 'namespace:remotes'
```

```r
> packageVersion('remotes')
[1] ‘1.1.1’
```

**Comment by maelle** [comment]
:woman_facepalming: thank you!

**Comment by maelle** [comment]
I still get an error though https://travis-ci.org/maelle/trying.lockedata.starters/builds/480819409

**Comment by maelle** [comment]
maybe I should not use "::" because tic tries to install covrpage despite my installing it?

**Comment by maelle** [comment]
Note that I wouldn't want `covrpage` to be listed in DESCRIPTION.

**Comment by maelle** [comment]
new error :thinking: https://travis-ci.org/maelle/trying.lockedata.starters/builds/480830490#L2064

**Comment by yonicd** [comment]
does it run locally on the repo clone?

**Comment by maelle** [comment]
good idea, will test.

**Comment by maelle** [comment]
_that_ can't be the problem, I only have a dummy test checking that 2*2==4 :joy_cat:
